name: etpe_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - numpy>=1.24,<2.3
  - pandas>=1.5
  - matplotlib>=3.7
  - seaborn>=0.12
  - scikit-learn>=1.2
  - xgboost>=2.0
  - scipy>=1.9
  - statsmodels>=0.14
  - pmdarima>=2.0,<2.3
  - joblib>=1.2
  - pyarrow
  - pip
  - notebook
  - pip:
      - wbdata>=0.3
      - pycountry>=22.3.5
